CREATE DATABASE IF NOT EXISTS groupbuy_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE groupbuy_db;

-- 어드민 사용자
CREATE TABLE IF NOT EXISTS admin_user (
    USER_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL UNIQUE,
    USER_PWD VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    USE_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
    APPEND_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 공동구매
CREATE TABLE IF NOT EXISTS group_buy (
    GROUP_BUY_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    PRODUCT_URL VARCHAR(500) NULL,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    PRODUCT_IMAGE_URL VARCHAR(500) NULL,
    PRODUCT_DESCRIPTION TEXT NULL,
    IMPORTER_NAME VARCHAR(100) NULL,
    ORIGINAL_PRICE INT NOT NULL DEFAULT 0,
    GROUPBUY_PRICE INT NOT NULL,
    TARGET_QUANTITY INT NOT NULL,
    MAX_QUANTITY INT NULL,
    MIN_PER_USER INT NOT NULL DEFAULT 1,
    MAX_PER_USER INT NULL,
    START_AT DATETIME NOT NULL,
    END_AT DATETIME NOT NULL,
    DELIVERY_DATE DATE NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'RECRUITING',
    CURRENT_QUANTITY INT NOT NULL DEFAULT 0,
    PARTICIPANT_COUNT INT NOT NULL DEFAULT 0,
    USE_YN VARCHAR(1) NOT NULL DEFAULT 'Y',
    APPEND_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 참여
CREATE TABLE IF NOT EXISTS participation (
    PARTICIPATION_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    GROUP_BUY_NO BIGINT NOT NULL,
    USER_EMAIL VARCHAR(200) NOT NULL,
    USER_DISPLAY_NAME VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    EXPECTED_AMOUNT INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    APPEND_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CANCELLED_AT DATETIME NULL,
    CONSTRAINT FK_PARTICIPATION_GROUPBUY FOREIGN KEY (GROUP_BUY_NO) REFERENCES group_buy(GROUP_BUY_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 초기 어드민 계정 (ID: admin@marketbang.kr / PW: admin1234)
INSERT IGNORE INTO admin_user (USER_ID, USER_PWD, USER_NAME, USE_YN, APPEND_DATE)
VALUES ('admin@marketbang.kr', '{bcrypt}$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '관리자', 'Y', NOW());
